default_agent: segmentation_agent
agents:
  segmentation_agent:
    name: segmentation_agent
    entrypoint: /Users/ajrav/Documents/TelecomGTMS/Customer Engagements/BT/BT Networks/ngde-bt/customer_behavior_agent/customer-behaviour-prediction-segmentation/segmentation-agent/segmentation_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/ajrav/Documents/TelecomGTMS/Customer Engagements/BT/BT Networks/ngde-bt/customer_behavior_agent/customer-behaviour-prediction-segmentation/segmentation-agent
    aws:
      execution_role: arn:aws:iam::076307688447:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-78cedb1d86
      execution_role_auto_create: false
      account: 076307688447
      region: us-east-1
      ecr_repository: 076307688447.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-segmentation_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: segmentation_agent-QWOc38E180
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:076307688447:runtime/segmentation_agent-QWOc38E180
      agent_session_id: c5d58076-2971-486d-b3bf-834289c95897
    codebuild:
      project_name: bedrock-agentcore-segmentation_agent-builder
      execution_role: arn:aws:iam::076307688447:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-78cedb1d86
      source_bucket: bedrock-agentcore-codebuild-sources-076307688447-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
